
version: "3.7"

services:
  mongo:
    image: mongo:latest
    container_name: mongo_bridge
    ports:
      - '27016:27017'
    environment:
      - MONGO_INITDB_DATABASE=bridge
    volumes:
      - ./db:/data/db
  web:
    image: kromsten/scrt-eth-bridge:0.1
    build: .
    container_name: web_bridge
    ports:
      - '3000:3000'
    volumes:
      - node_modules:/app/node_modules
    restart: 'unless-stopped'
    depends_on:
      - mongo

volumes:
  node_modules:
    driver: local